global:
  govcloud: true
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-mcafee-epo
  regions:
    - us-gov-east-1

  reporting: true
tests:
  mcafee-epo-t1:
    regions:
      - us-gov-east-1
    template_file: mcafee-epo-gov-cloud-master.template
    parameter_input: stack-params-us-gov-east-1.json 

